### ISSUE TITLE
Request for adding the nine-box model to AIBECS

### ISSUE THREAD

**Issue by briochemc** [ThomasHaine/Pedagogical-Tracer-Box-Model#1]
Dear Prof. Haine,

Google notified me of your nice preprint on Green's functions, which led me here. I played a little with the code: It looks very neat so thank you for sharing it!

I would like to kindly request permission to add your 9-box circulation model to the circulation models available in [AIBECS.jl](https://github.com/JuliaOcean/AIBECS.jl) (which I would be happy to introduce in more detail to you). If you are OK with this I think I can find all I need in the preprint and code. 

Please let me know,
Best Regards,
Benoit Pasquier

**Comment by ThomasHaine** [comment]
Hi @briochemc. Thanks for your interest!  Yes, please add the model to the [AIBECS.jl ](https://github.com/JuliaOcean/AIBECS.jl) repo, which looks very nice. Be aware that co-author @ggebbie is working on a Julia version of the MATLAB code here. It will be included with the JAMES paper when it's a bit more mature. So it may be easiest to collaborate with Jake.

**Comment by briochemc** [comment]
OK great! Thanks! I will add it when I find the time :)

**Comment by briochemc** [comment]
BTW I think it's a great idea to port this to Julia @ggebbie! Is it going to be a Pluto notebook? Don't hesitate to include me if you think I can help :)

**Comment by ggebbie** [comment]
Hi @briochemc @ThomasHaine ,  While the porting to Julia is not complete, I've made a lot of progress. The Julia repository is now public at https://github.com/ggebbie/OceanGreensFunctionMethods.jl .

A Pluto notebook is available here:
https://github.com/ggebbie/OceanGreensFunctionMethods.jl/blob/main/notebooks/pedagogical_box_model.html

Any help in porting to AIBECS and addressing numerous listed GitHub Issues is appreciated!
